language: python
python:
  - "2.7"
virtualenv:
    system_site_packages: true
install:
  - sudo apt-get install python-numpy python-scipy msgpack-python python-nose libatlas-dev
  - python setup.py build_ext --inplace
script:  nosetests
